fullnameOverride: kiali

auth:
  strategy: anonymous

deployment:
  accessible_namespaces:
    - "**"

external_services:
  prometheus:
    url: http://kube-prometheus-stack-prometheus.shop-msa-platform.svc.cluster.local:9090
  grafana:
    enabled: true
    in_cluster_url: http://kube-prometheus-stack-grafana.shop-msa-platform.svc.cluster.local/grafana
    url: https://dev-shop.wookja.cloud/grafana
  tracing:
    enabled: false

server:
  web_root: /kiali
