apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: INTERNAL_API_URL
              value: http://nginx
            - name: NEXT_PUBLIC_API_URL
          image: frontend
          name: frontend
      restartPolicy: Always
