apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: payment-event-service
  name: payment-event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-event-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: payment-event-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@payment-event-db.shop-msa-app.svc.cluster.local:5432/paymenteventdb
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.shop-msa-app.svc.cluster.local:9092
            - name: KAFKA_GROUP_ID
              value: payment-event-service
            - name: KAFKA_TOPIC_PAYMENT_CREATED
              value: payment-created
            - name: REDIS_URL
              value: redis://redis:6379
          image: ghcr.io/pony4021/payment-event-service:latest
          name: payment-event-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
