apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              value: admin@admin.com
            - name: ADMIN_PASSWORD
              value: adminadmin1234
            - name: ADMIN_USERNAME
              value: admin
            - name: DATABASE_URL
              value: postgresql+asyncpg://user:user_db_password@user-db:5432/userdb
            - name: JWT_ALGORITHM
              value: HS256
            - name: JWT_EXPIRE_MINUTES
              value: "60"
            - name: JWT_EXPIRE_MINUTES_ADMIN
              value: "30"
            - name: JWT_EXPIRE_MINUTES_USER
              value: "60"
            - name: JWT_SECRET_KEY
              value: your-very-strong-secret-key-change-this
            - name: REDIS_URL
              value: redis://redis:6379
          image: user-service
          name: user-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
