apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# skeleton overlay for prod rollout
patchesStrategicMerge:
  - patch-replicas-prod.yaml
  - patch-resources-prod.yaml
  - patch-istio-host-prod.yaml
  - patch-configmap-prod.yaml
