apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-admin
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-event-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-admin
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service
  namespace: shop-msa-app
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-event-service
  namespace: shop-msa-app
$patch: delete

