apiVersion: v1
kind: Secret
metadata:
  name: shop-msa-app-secrets
  namespace: shop-msa-app
type: Opaque
stringData:
  # Local in-cluster Postgres Services
  USER_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@user-db.shop-msa-app.svc.cluster.local:5432/userdb
  PRODUCT_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@product-db.shop-msa-app.svc.cluster.local:5432/productdb
  ORDER_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@order-db.shop-msa-app.svc.cluster.local:5432/orderdb
  INVENTORY_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@inventory-db.shop-msa-app.svc.cluster.local:5432/inventorydb
  PAYMENT_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@payment-db.shop-msa-app.svc.cluster.local:5432/paymentdb
  PAYMENT_EVENT_DATABASE_URL: postgresql+asyncpg://shopmsa:CHANGE_ME_DB_PASSWORD@payment-event-db.shop-msa-app.svc.cluster.local:5432/paymenteventdb

