apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: frontend-admin
  name: frontend-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-admin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: frontend-admin
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - env:
            - name: ADMIN_API_INTERNAL_URL
              value: http://nginx
            - name: INTERNAL_API_URL
              value: http://nginx
            - name: NEXT_PUBLIC_API_URL
          image: ghcr.io/pony4021/frontend-admin:latest
          name: frontend-admin
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
