apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-msa-observability-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/infra/platform/helm-values/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/REPLACE_ME/shop-msa.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: shop-msa-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
