apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/namespaces.yaml
  - infra/app-configmap.yaml
  - infra/app-secrets.yaml
  - infra/networkpolicy.yaml
  - infra/storageclass-efs.yaml
  - infra/storageclass-gp3.yaml
  - infra/istio-gateway.yaml
  - infra/istio-virtualservice.yaml
  - infra/istio-destinationrule.yaml
  - infra/istio-peerauthentication.yaml
  - infra/db/user-db-deployment.yaml
  - infra/db/user-db-data-persistentvolumeclaim.yaml
  - infra/db/product-db-deployment.yaml
  - infra/db/product-db-data-persistentvolumeclaim.yaml
  - infra/db/order-db-deployment.yaml
  - infra/db/order-db-data-persistentvolumeclaim.yaml
  - infra/db/inventory-db-deployment.yaml
  - infra/db/inventory-db-data-persistentvolumeclaim.yaml
  - infra/db/payment-db-deployment.yaml
  - infra/db/payment-db-data-persistentvolumeclaim.yaml
  - infra/db/payment-event-db-deployment.yaml
  - infra/db/payment-event-db-data-persistentvolumeclaim.yaml
  - infra/redis-deployment.yaml
  - infra/kafka-deployment.yaml
  - infra/nginx-deployment.yaml
  - infra/nginx-cm0-configmap.yaml
  - jobs/kafka-topic-init-job.yaml
  - apps/frontend.yaml
  - apps/frontend-admin.yaml
  - apps/user-service.yaml
  - apps/product-service.yaml
  - apps/order-service.yaml
  - apps/inventory-service.yaml
  - apps/payment-service.yaml
  - apps/payment-event-service.yaml
