apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/frontend
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/frontend-admin
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/user-service
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/product-service
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/order-service
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/inventory-service
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/payment-service
    newTag: dev-<gitsha>
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/payment-event-service
    newTag: dev-<gitsha>

patchesStrategicMerge:
  - patch-istio-host-dev.yaml
  - patch-storageclass-efs-dev.yaml
  - patch-secrets-dev.yaml
