apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/frontend
    newName: ghcr.io/pony4021/msa-shop/frontend–260410-01
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/frontend-admin
    newName: ghcr.io/pony4021/msa-shop/frontend-admin–260427-01
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/user-service
    newName: msa-shop-user-service
    newTag: latest
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/product-service
    newName: msa-shop-product-service
    newTag: latest
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/order-service
    newName: ghcr.io/pony4021/msa-shop/order-service–260427-01
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/inventory-service
    newName: msa-shop-inventory-service
    newTag: latest
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/payment-service
    newName: msa-shop-payment-service
    newTag: latest
  - name: <aws_account_id>.dkr.ecr.ap-northeast-2.amazonaws.com/shop-msa/payment-event-service
    newName: msa-shop-payment-event-service
    newTag: latest

patchesStrategicMerge:
  - patch-istio-host-dev.yaml
  - patch-storageclass-efs-dev.yaml
  - patch-secrets-dev.yaml
